[Desktop Entry]
Name=Mobile Logger plugin
Name[ca]=Connector del registre del mòbil
Name[ca@valencia]=Connector del registre del mòbil
Name[de]=Modul „Mobile Logger“
Name[en_GB]=Mobile Logger plugin
Name[es]=Complemento de registro del móvil
Name[et]=Mobile sisselogimise plugin
Name[fr]=Module complémentaire d'enregistreur de journaux mobile
Name[gl]=Complemento de rexistro de móbil
Name[it]=Estensione di registro per Mobile
Name[ko]=모바일 기록 플러그인
Name[nl]=Plug-in voor loggen van mobiel
Name[nn]=Programtillegg for mobillogg
Name[pl]=Wtyczka logowania na urządzenia mobilne
Name[pt]='Plugin' de Registos Móveis
Name[sl]=Mobilni vtičnik za pisanje dnevnika
Name[sv]=Mobilt loggningsinsticksprogram
Name[tg]=Васлкунаки сабткунии мобилӣ
Name[tr]=Mobil Günlük eklentisi
Name[uk]=Додаток ведення мобільного журналу
Name[x-test]=xxMobile Logger pluginxx
Name[zh_CN]=移动日志插件
Name[zh_TW]=行動紀錄器外掛程式
Comment=Provides integration with Telepathy Logger
Comment[ca]=Aquest connector proporciona integració amb l'enregistrador del Telepathy
Comment[ca@valencia]=Aquest connector proporciona integració amb l'enregistrador del Telepathy
Comment[cs]=Poskytuje integraci se zaznamenáváním Telepathy
Comment[de]=Stellt Integration mit Telepathy-Protokollen zur Verfügung
Comment[el]=Παρέχει ολοκλήρωση με τον καταγραφέα Telepathy
Comment[en_GB]=Provides integration with Telepathy Logger
Comment[es]=Proporciona integración con el registrador de Telepathy
Comment[et]=Lõimimine Telepathy logimisprogrammiga
Comment[fr]=Fournit une Intégration avec l'enregistreur de journaux Telepathy
Comment[gl]=Fornece integración co rexistro de Telepathy
Comment[it]=Fornisce l'integrazione con Telepathy Logger
Comment[ko]=Telepathy 로거와 통합 제공
Comment[nl]=Biedt integratie met loggen van Telepathy
Comment[nn]=Gjev integrasjon med Telepathy-loggaren
Comment[pl]=Zapewnia integrację z dziennikiem Telepathy
Comment[pt]=Oferece a integração com o sistema de registo Telepathy Logger
Comment[sk]=Poskytuje integráciu so záznamom Telepathy
Comment[sl]=Nudi integracijo s programom za pisanjem dnevnika Telepathy Logger
Comment[sv]=Tillhandahåller integrering med Telepathy-loggningsprogram
Comment[tg]=Барои барномаи сабткунии интиқоли фикрҳо ҳампайвандиро таъмин менамояд
Comment[tr]=Telephaty Günlükleme ile bütünleştirme sağlar
Comment[uk]=Забезпечує інтеграцію з засобом ведення журналу Telepathy
Comment[x-test]=xxProvides integration with Telepathy Loggerxx
Comment[zh_CN]=提供与 Telepathy 日志的集成
Comment[zh_TW]=提供 Telepathy 紀錄器的整合

ServiceTypes=KTpLogger/Plugin

X-KDE-Library=ktploggerplugin_mobile
X-KDE-PluginInfo-Author=Martin Klapetek
X-KDE-PluginInfo-Email=mklapetek@kde.org
X-KDE-PluginInfo-Name=mobile
X-KDE-PluginInfo-Version=1.0
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=LGPL
X-KTp-PluginInfo-Version=1
Encoding=UTF-8
Type=Service
