[Desktop Entry]
Name=Mobile Logger plugin
Name[ca]=Connector del registre del mòbil
Name[ca@valencia]=Connector del registre del mòbil
Name[en_GB]=Mobile Logger plugin
Name[nl]=Plug-in voor loggen van mobiel
Name[nn]=Programtillegg for mobillogg
Name[pl]=Wtyczka logowania na urządzenia mobilne
Name[pt]='Plugin' de Registos Móveis
Name[sv]=Mobilt loggningsinsticksprogram
Name[uk]=Додаток ведення мобільного журналу
Name[x-test]=xxMobile Logger pluginxx
Name[zh_TW]=行動紀錄器外掛程式
Comment=Provides integration with Telepathy Logger
Comment[ca]=Aquest connector proporciona integració amb l'enregistrador del Telepathy
Comment[ca@valencia]=Este connector proporciona integració amb l'enregistrador del Telepathy
Comment[de]=Stellt Integration mit Telepathy-Protokollen zur Verfügung
Comment[en_GB]=Provides integration with Telepathy Logger
Comment[nl]=Biedt integratie met loggen van Telepathy
Comment[nn]=Gjev integrasjon med Telepathy-loggaren
Comment[pl]=Zapewnia integrację z dziennikiem Telepathy
Comment[pt]=Oferece a integração com o sistema de registo Telepathy Logger
Comment[sv]=Tillhandahåller integrering med Telepathy-loggningsprogram
Comment[uk]=Забезпечує інтеграцію з засобом ведення журналу Telepathy
Comment[x-test]=xxProvides integration with Telepathy Loggerxx
Comment[zh_TW]=提供 Telepathy 紀錄器的整合

ServiceTypes=KTpLogger/Plugin

X-KDE-Library=ktploggerplugin_mobile
X-KDE-PluginInfo-Author=Martin Klapetek
X-KDE-PluginInfo-Email=mklapetek@kde.org
X-KDE-PluginInfo-Name=mobile
X-KDE-PluginInfo-Version=1.0
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=LGPL
X-KTp-PluginInfo-Version=1
Encoding=UTF-8
Type=Service
